// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ6Qe7ByOkCie80qVP1J0myhY-hurvsK8',
    appId: '1:386225928145:web:86f42b7ecc970c0a1bd2f0',
    messagingSenderId: '386225928145',
    projectId: 'vegetasi-app-39759',
    authDomain: 'vegetasi-app-39759.firebaseapp.com',
    storageBucket: 'vegetasi-app-39759.appspot.com',
    measurementId: 'G-9XKJJXNYSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPDUrd8qW_l9oAZB7vpuoVb8vusXsWHH0',
    appId: '1:386225928145:android:a6eb927a33aa10131bd2f0',
    messagingSenderId: '386225928145',
    projectId: 'vegetasi-app-39759',
    storageBucket: 'vegetasi-app-39759.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzZcfKLuDgPQ0i1jOB08aT0FxK4ycBGI',
    appId: '1:386225928145:ios:08bcb24f581279c91bd2f0',
    messagingSenderId: '386225928145',
    projectId: 'vegetasi-app-39759',
    storageBucket: 'vegetasi-app-39759.appspot.com',
    iosBundleId: 'com.example.vegetasiApp',
  );
}
